apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: il5neighn-python 
  janus-idp.io/tekton: il5neighn-python
  backstage.io/kubernetes-id: il5neighn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: il5neighn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml