apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: il5neighn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: il5neighn-python 
  name: il5neighn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: il5neighn-python 
